### ISSUE TITLE
Undefined function or variable 'normalizecols'.

### ISSUE THREAD

**Issue by tristanstoeber** [pillowlab/LNPfitting#1]
Hey,
upon running tutorial1_MID_tfilter.m on a matlab r2016a, i receive the following bug report:

>> tutorial1_MID_tfilter
Number of spikes in training dataset: 3060
Computing STA and STC...
Computing top iSTAC filter...
Pruning out 14 dimensions (out of 32) from raw stimuli
 Stripped off dimension 1, KL div=[0.3401 0.3401]
Undefined function or variable 'normalizecols'.

Error in makeBasis_StimKernel (line 59)
kbasis = normalizecols(kbasis);

Error in makeFittingStruct_LNP (line 53)
    ktbas = makeBasis_StimKernel(ktbasprs,nkt);

Error in tutorial1_MID_tfilter (line 87)
gg0 = makeFittingStruct_LNP(filt0,RefreshRate,mask); % create LNP fitting structure

**Comment by jpillow** [comment]
Hi Tristan,

Thanks for flagging this and apologies for the error. I've added the
'normalizecols.m' function to the repository.

I should add that this repo is not finished yet and there may be other
problems lurking. I'm hoping to finish it up in the next month!

best,
Jonathan
